// examples/news/plugins/reuters_plugin/ui/src/ReutersPanel.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';

interface ReutersPanelProps {
  pluginId?: string;
}

const props = withDefaults(defineProps<ReutersPanelProps>(), {
  pluginId: 'reuters_plugin',
});

const dateline = ref('LONDON');
const note = ref('');
const flash = ref<{ type: 'success' | 'error'; text: string } | null>(null);

const DATELINE_OPTIONS = [
  { label: 'London', value: 'LONDON' },
  { label: 'New York', value: 'NEW YORK' },
  { label: 'Tokyo', value: 'TOKYO' },
  { label: 'Hong Kong', value: 'HONG KONG' },
];

interface DemoRow {
  key: string;
  city: string;
  region: string;
}

const demoData: DemoRow[] = [
  { key: '1', city: 'London', region: 'Europe' },
  { key: '2', city: 'New York', region: 'Americas' },
  { key: '3', city: 'Tokyo', region: 'Asia' },
  { key: '4', city: 'Hong Kong', region: 'Asia' },
];

const demoColumns = [
  { title: '城市', key: 'city' },
  { title: '地区', key: 'region' },
];

onMounted(() => {
  const raw = localStorage.getItem(`plugin-settings-${props.pluginId}`);
  if (raw) {
    try {
      const s = JSON.parse(raw) as { dateline?: string; note?: string };
      if (typeof s.dateline === 'string') dateline.value = s.dateline;
      if (typeof s.note === 'string') note.value = s.note;
    } catch {
      /* ignore malformed settings */
    }
  }
});

function handleSave(): void {
  try {
    localStorage.setItem(
      `plugin-settings-${props.pluginId}`,
      JSON.stringify({ dateline: dateline.value, note: note.value }),
    );
    flash.value = { type: 'success', text: '设置已保存' };
  } catch {
    flash.value = { type: 'error', text: '保存失败,请重试' };
  }
  setTimeout(() => {
    flash.value = null;
  }, 2000);
}
</script>

<template>
  <n-card title="📰 路透社控制面板" style="max-width: 720px;">
    <n-space vertical :size="24">
      <n-form label-placement="top">
        <n-form-item label="电头 (Dateline)">
          <n-select v-model:value="dateline" :options="DATELINE_OPTIONS" />
        </n-form-item>
        <n-form-item label="备注">
          <n-input v-model:value="note" placeholder="输入备注信息" clearable />
        </n-form-item>
        <n-form-item label="当前插件 ID">
          <n-input :value="pluginId" disabled />
        </n-form-item>
        <n-button type="primary" @click="handleSave">💾 保存设置</n-button>
      </n-form>
      <n-card title="电头演示数据" size="small" embedded>
        <n-data-table
          :columns="demoColumns"
          :data="demoData"
          :pagination="false"
          size="small"
        />
      </n-card>
      <n-alert v-if="flash" :type="flash.type" :title="flash.text" />
    </n-space>
  </n-card>
</template>

// reuters_plugin/ui/src/ReutersPanel.tsx
/**
 * 路透社插件 React 面板（qiankun 子应用版本）
 *
 * 之前由宿主注入 React / createRoot；现在此项目独立打包 React，
 * 由 vite-plugin-qiankun 在 qiankun 容器中挂载。
 */

import { useState, useCallback, useEffect } from 'react';

interface ReutersPanelProps {
  pluginId?: string;
}

export function ReutersPanel({ pluginId = 'reuters_plugin' }: ReutersPanelProps) {
  const [dateline, setDateline] = useState('LONDON');
  const [status, setStatus] = useState<'saving' | 'success' | 'error' | null>(null);

  const api = {
    async getSettings(id: string): Promise<Record<string, unknown> | null> {
      try {
        const raw = localStorage.getItem(`plugin-settings-${id}`);
        return raw ? JSON.parse(raw) : null;
      } catch {
        return null;
      }
    },
    async saveSettings(id: string, settings: Record<string, unknown>): Promise<void> {
      localStorage.setItem(`plugin-settings-${id}`, JSON.stringify(settings));
    },
  };

  useEffect(() => {
    api.getSettings(pluginId)
      .then((s) => {
        if (s && typeof s.dateline === 'string') setDateline(s.dateline);
      })
      .catch(() => undefined);
  }, [pluginId]);

  const handleSave = useCallback(async () => {
    setStatus('saving');
    try {
      await api.saveSettings(pluginId, { dateline });
      setStatus('success');
      setTimeout(() => setStatus(null), 2000);
    } catch {
      setStatus('error');
      setTimeout(() => setStatus(null), 2000);
    }
  }, [dateline, pluginId]);

  return (
    <div className="plugin-panel">
      <h3 className="panel-title">📰 路透社控制面板</h3>
      <p className="panel-desc">配置路透社的电头（dateline）偏好设置</p>

      <div className="field">
        <label className="field-label">电头 (Dateline)</label>
        <input
          className="field-input"
          value={dateline}
          onChange={(e) => setDateline(e.target.value)}
          placeholder="如 LONDON, NEW YORK…"
        />
      </div>

      <div className="field">
        <label className="field-label">当前插件 ID</label>
        <code className="field-code">{pluginId}</code>
      </div>

      <button
        className="btn btn-primary"
        onClick={handleSave}
        disabled={status === 'saving'}
      >
        {status === 'saving' ? '⏳ 保存中…' : '💾 保存设置'}
      </button>

      {status === 'success' && <p className="msg success">✅ 设置已保存</p>}
      {status === 'error' && <p className="msg error">❌ 保存失败，请重试</p>}
    </div>
  );
}

export default ReutersPanel;
